### ISSUE TITLE
Too much white space above loop sequences in the variable bank

### ISSUE THREAD

**Issue by dmaya99** [awb-carleton/practicum#22]

**Comment by ankit8697** [comment]
This seems to be caused by the index row above the array taking up space. I know it isn't actually shown but the top line of the array is actually a part of the index row, so hiding it hides the top border of the array as well. So the only way to fix it it seems is to either change the way that line is drawn or do something fancy with CSS that would allow the upper border of the index row (it's the tr that is the parent of ".bank_variable_array_index") to be below the actual content.
